#!/usr/bin/sh

PREFIX="/opt/n64-toolchain"
BINUTILS="../binutils.tar.gz"
GCC="../gcc.tar.gz"
NEWLIB="../newlib.tar.gz"


set -e
rm -rf $PREFIX
rm -rf binutils
rm -rf gcc
rm -rf newlib
rm -rf build-binutils
rm -rf build-bootstrap-gcc
rm -rf build-newlib
rm -rf build-gcc

export PATH="$PREFIX/bin:$PATH"
export CFLAGS_FOR_TARGET="-ffunction-sections -fdata-sections"
export CXXFLAGS_FOR_TARGET="-ffunction-sections -fdata-sections"
export AR_FOR_TARGET="mips64-gcc-ar"
export NM_FOR_TARGET="mips64-gcc-nm"
export RANLIB_FOR_TARGET="mips64-gcc-ranlib"

mkdir binutils
tar xzvf $BINUTILS --strip-components=1 -C binutils
mkdir build-binutils
cd build-binutils
../binutils/configure\
 --prefix="$PREFIX" --target=mips64\
 --disable-nls\
 LDFLAGS="--static"
make all
make install
cd ..

mkdir gcc
tar xzvf $GCC --strip-components=1 -C gcc
cd gcc
./contrib/download_prerequisites
cd ..
mkdir build-bootstrap-gcc
cd build-bootstrap-gcc
../gcc/configure\
 --prefix="$PREFIX" --target=mips64\
 --with-tune=vr4300 --with-arch=vr4300 --with-abi=32\
 --with-newlib --without-headers\
 --disable-shared --disable-multiarch --disable-multilib --disable-__cxa_atexit\
 --disable-nls\
 --enable-languages=c,c++,lto\
 LDFLAGS="--static"
make all-gcc
make install-gcc
cd ..

mkdir newlib
tar xzvf $NEWLIB --strip-components=1 -C newlib
mkdir build-newlib
cd build-newlib
../newlib/configure\
 --prefix="$PREFIX" --target=mips64\
 --with-newlib
make all
make install
cd ..

mkdir build-gcc
cd build-gcc
../gcc/configure\
 --prefix="$PREFIX" --target=mips64\
 --with-tune=vr4300 --with-arch=vr4300 --with-abi=32\
 --with-newlib\
 --disable-shared --disable-multiarch --disable-multilib --disable-__cxa_atexit\
 --disable-nls\
 --enable-languages=c,c++,lto\
 LDFLAGS="--static"
make all
make install
cd ..
